# Generated by Django 4.1.5 on 2023-12-22 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testmanagementboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=255)),
                ('expected_result', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testmanagementboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('pre_conditions', models.TextField(blank=True, null=True)),
                ('post_conditions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('DESIGN', 'Design'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelado')], max_length=20)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('NORMAL', 'Normal'), ('LOW', 'Low')], max_length=10)),
                ('estimated_time', models.PositiveIntegerField(default=0)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testmanagementboard.testsuite')),
                ('test_steps', models.ManyToManyField(related_name='test_cases', to='testmanagementboard.teststeps')),
            ],
        ),
    ]
