# Generated by Django 4.1.5 on 2023-12-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanagementboard', '0002_teststeps_testsuite_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='parameters',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='title',
            field=models.TextField(),
        ),
    ]
