# Generated by Django 4.1.5 on 2023-12-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testmanagementboard', '0003_testcase_parameters_alter_testcase_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestSteps',
            new_name='TestStep',
        ),
    ]
