# Generated by Django 4.1.5 on 2023-12-22 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testmanagementboard', '0006_release_test_suite_alter_testcase_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='project',
        ),
        migrations.AddField(
            model_name='defect',
            name='release',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testmanagementboard.release'),
            preserve_default=False,
        ),
    ]
