# Generated by Django 4.1.5 on 2023-12-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanagementboard', '0009_alter_testcase_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('value', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='parameters',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='state',
            field=models.CharField(choices=[('DESIGN', 'Design'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='title',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='parameters',
            field=models.ManyToManyField(related_name='test_case_parameters', to='testmanagementboard.parameter'),
        ),
    ]
