# Generated by Django 4.1.5 on 2023-12-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanagementboard', '0010_parameter_remove_testcase_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='releases',
            field=models.ManyToManyField(blank=True, related_name='project_releases', to='testmanagementboard.release'),
        ),
    ]
