# Generated by Django 4.1.5 on 2023-12-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanagementboard', '0011_project_releases'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test_cases',
            field=models.ManyToManyField(blank=True, related_name='project_test_cases', to='testmanagementboard.testcase'),
        ),
    ]
