# Generated by Django 4.1.5 on 2023-12-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanagementboard', '0012_project_test_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='version',
            field=models.TextField(default=''),
        ),
    ]
