# Generated by Django 4.1.5 on 2023-12-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanagementboard', '0013_release_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
