# Generated by Django 4.1.5 on 2023-12-23 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testmanagementboard', '0014_alter_defect_id_alter_testcase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testmanagementboard.project'),
            preserve_default=False,
        ),
    ]
