# Generated by Django 4.1.5 on 2023-12-23 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testmanagementboard', '0015_testcase_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teststepexecution',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='teststepexecution',
            name='description',
        ),
        migrations.AddField(
            model_name='teststepexecution',
            name='defect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testmanagementboard.defect'),
        ),
        migrations.AlterField(
            model_name='testcaseexecution',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAIL', 'Fail'), ('ON_GOING', 'On Going')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teststepexecution',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAIL', 'Fail'), ('ON_GOING', 'On Going')], max_length=20),
        ),
    ]
