# Generated by Django 4.1.5 on 2023-12-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanagementboard', '0016_remove_teststepexecution_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='test_steps',
        ),
        migrations.AddField(
            model_name='defect',
            name='test_replication_steps',
            field=models.ManyToManyField(blank=True, null=True, related_name='defect_steps', to='testmanagementboard.defectreplicationstep'),
        ),
        migrations.AddField(
            model_name='defect',
            name='test_step',
            field=models.ManyToManyField(blank=True, null=True, related_name='broken_test_step', to='testmanagementboard.teststep'),
        ),
    ]
